spring:
    datasource:
          url: jdbc:postgresql://localhost:5432/crowdfunding_dp
          username: crowdfunding
          password: 12345
    jpa:
          hibernate:
                ddl-auto: create-drop
