spring:
    datasource:
          url: jdbc:postgresql://localhost:5432/crowdfunding_dp
          username: crowdfunding
          password: 12345
    flyway:
      user: crowdfunding
      password: 12345
      schemas: public
